Issue 16 - Translation to English (翻译成英文)
chengstone/cchess-zero pull request #17
Opened 2021-10-30 01:15 UTC by ycechungAI

I was able to fix some links as well.

With each paragraph i translated the corresponding English text below.
With each title or code or comment I translated inline if the spacing allows for it

2021-10-30 01:15 UTC, ycechungAI commented
completes #16

2021-10-30 10:56 UTC, ycechungAI reviewed
reviewed

2021-11-11 03:09 UTC, chengstone commented
Hi, I will review those changes ASAP. Thank you.

2021-11-11 03:46 UTC, chengstone reviewed
Based on the country code, it's better to use CN for China instead of ch

2021-11-11 03:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "In fact, you can see many practical projects about AlphaGo on GitHub, including [`Chess`](https://github.com/Zeta36/chess-alpha-zero), [`Go`](https://github.com/gcp/leela-zero), [`Gomoku`](https
I think Chinese words "等等" here means etc. not "wait"

2021-11-11 14:22 UTC, ycechungAI reviewed
made the changes

2021-11-11 14:23 UTC, ycechungAI commented on cchess-zero.ipynb
> +    "In fact, you can see many practical projects about AlphaGo on GitHub, including [`Chess`](https://github.com/Zeta36/chess-alpha-zero), [`Go`](https://github.com/gcp/leela-zero), [`Gomoku`](https
I used etc and made the change

2021-11-12 14:41 UTC, chengstone commented
review done for now, please fix the issues

2021-11-18 12:44 UTC, ycechungAI commented
Hi @chengstone , I made the changes

2021-11-19 01:51 UTC, chengstone commented
Hi @ycechungAI , seems there is still has almost 56 pending comments that you don't fix, please fix it.

2021-11-23 01:46 UTC, chengstone requested changes
Oh, sorry, I forgot submit review, all comments you can see now

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "I’m not talented, Xian Chou translated these two papers. The time is short and the level is limited ✧(≖ ◡ ≖✿), if you are not familiar with English, I hope these two translations can provide som
“小弟不才，献丑翻译了这两篇论文，” is Chinese polite remarks, 
so I think just translate to "I translated these two papers" instead of "I’m not talented, Xian Chou translated these two papers." is enough

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "(ycechungAI: thats why I am here to help =) )"
Thank you so much for your kind help! ^_^

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "- d. Once the MCTS search is completed, the probability π of returning to position s is proportional to $N^{1 /τ}$, where N is the count of visits for each move from the root state, and τ is the
This a~d part basically you are right, but for more precisely purpose, we should use the original descriptions of the papers here I think:
a Each simulation traverses the tree by selecting the edge with maximum action-value Q, plus an upper confidence bound U that depends on a stored prior probability P and visit count N for that edge (which is incremented once traversed). 
b The leaf node is expanded and the associated position s is evaluated by the neural network (P (s, ·), V (s)) = f θ (s); the vector of P values are stored in the outgoing edges from s. 
c Action-values Q are updated to track the mean of all evaluations V in the subtree below that action. 
d Once the search is complete, search probabilities π are returned, proportional to N 1/τ , where N is the visit count of
each move from the root state and τ is a parameter controlling temperature.

For more details you can refer to the original paper:
https://www.researchgate.net/publication/320473480_Mastering_the_game_of_Go_without_human_knowledge

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "After the calculation, I know which action has the largest Q+U value in the current situation, and the situation after this action moves is the current situation of the second simulation. For ex
The translations of "当头炮" are not uniform.
please change "biggest shot", "top shot" and "headshot" to "Central Cannon" for whole doc.

As wikipedia said: "当头炮" also means "立中炮"
https://zh.wikipedia.org/zh-my/%E4%B8%AD%E5%9C%8B%E8%B1%A1%E6%A3%8B%E8%A1%93%E8%AA%9E

And "中炮" ’s english words is "Central Cannon"
http://wxf.ca/xq/computer/XIANGQI_TERMS_IN_ENGLISH.pdf

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Now it’s the second simulation. If the previous action was the headshot, we have to select the action following this situation, but this situation is a leaf node. That is to say, you can choose
Seems miss "当头炮" word in the "you can choose which actions you can choose after you don’t know", and there is repeat "you can choose"
I think should add "Central Cannon" after "after", become to:
which actions you can choose after Central Cannon you don’t know

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "In the words of the paper, c_puct is a constant that determines the level of exploration; this search control strategy initially tends to have high prior probability and low number of visits, bu
Original paper said:
"where c_puct is a constant determining the level of exploration; this search control strategy initially
prefers actions with high prior probability and low visit count, but asympotically prefers actions
with high action-value."

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "There is a place to pay attention to in the Expand and evaluate section. The paper said: The situation in the queue is evaluated by the neural network using a minimum batch size of 8; the search
For the "paper said" part, I know they are almost 100% the same, but I want to leave the original paper sentences here:
Positions in the queue are evaluated by the neural network using a mini-batch size of 8; the
search thread is locked until evaluation completes. The leaf node is expanded and each edge (s L , a)
is initialised to {N (s L , a) = 0, W (s L , a) = 0, Q(s L , a) = 0, P (s L , a) = p a }; the value v is then
backed up.

It is OK to use your translate version, modify or not it's on your choice.

2021-11-23 01:46 UTC, chengstone commented on README.en.md
> +Welcome to forward and spread ^_^
I think you can add your contact information or other content here as a translator.

2021-11-23 01:46 UTC, chengstone commented on README.en.md
> +知乎专栏：https://zhuanlan.zhihu.com/p/34433581
Zhihu column instead of "知乎专栏"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "The next step is the key point. Evaluate and Backup said together, let’s take a look at what Backup does: the statistical data of the edge is updated in reverse at each step t≤L. The visit count
For “Evaluate and Backup said together”, how about to use "discussed" instead of "said", I'm not so sure, since my English is not good, this part is up to your decision. : )

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "这个过程就是evaluate，是为了Backup步骤做准备。因为在Backup步骤，我们要用v来更新W和Q的，但是如果只做了一次Select，棋局还没有结束，此时的v是不明确的，必须要等到一盘棋完整的下完才能知道v到底是多少。就是说我现在下了一步棋，不管这步棋是好棋还是臭棋，只有下完整盘期分出胜负，才能给我下的这步棋评分。不管这步棋的得失，即使我这步棋丢了个车，但最后我赢了，那这个v就
Sorry, my bad, “只有下完整盘期分出胜负” should be "只有下完整盘棋分出胜负".
Should use 棋 not 期.
So the translations of the "period" maybe can be removed.
Become to "only by playing a complete game can I score the move"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "This process is evaluate, which is to prepare for the Backup step. Because in the Backup step, we need to use v to update W and Q, but if we only do Select once, the game is not over yet. At thi
The translations of "and we must wait until a game of chess is completed to know the end of v. how many." for "必须要等到一盘棋完整的下完才能知道v到底是多少。"
I think use "and we must wait until a game of chess is completed to know the value of v" is enough.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Then start to do Backup, \"The statistical data of the edge is updated in the reverse direction at each step t≤L. The access count increases, $N(s_t, a_t) = N(s_t, a_t) +1$, and the action value
The translations of "The statistical data of the edge is updated in the reverse direction at each step t≤L. The access count increases, $N(s_t, a_t) = N(s_t, a_t) +1$, and the action value is updated to the average value , $W(s_t, a_t) = W(s_t, a_t) + v, Q(s_t, a_t) = \frac{W(s_t ,a_t)}{N(s_t ,a_t)}$."

Original paper said:
The edge statistics are updated in a backward pass through each step
t ≤ L. The visit counts are incremented, $N(s_t, a_t) = N(s_t, a_t) +1$, and the action-value is updated
to the mean value, $W(s_t, a_t) = W(s_t, a_t) + v, Q(s_t, a_t) = \frac{W(s_t ,a_t)}{N(s_t ,a_t)}$.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Follow the above process to execute a~c. In the paper, 1600 simulations are executed for each move, that is, 1600 a~c. This MCTS process is the process of simulating self-play. After the simulat
How about use "1600 times a~c" instead of "1600 a ~ c".
And for the translations of "At the end of the search, AlphaGo Zero selects a move a at the root node s0, which is proportional to its visit count power exponent, $π(a |s_0) = \frac{N(s_0,a) ^{1/τ}}{\sum_b N(s_0,b)^{1/τ}}$, where τ is the temperature parameter that controls the exploration level. In the following The search tree is reused at the time step: the child node corresponding to the action of the move becomes the new root node; all the statistical information of the subtree below this node is retained, and the rest of the tree is discarded. If the value of the root node and If the value of the best child node is lower than the threshold $v_{resign}$, AlphaGo Zero will admit defeat."

The original paper said:
"At the end of the search AlphaGo Zero selects a move a to play in the root
position s0 , proportional to its exponentiated visit count, $π(a |s_0) = \frac{N(s_0,a) ^{1/τ}}{\sum_b N(s_0,b)^{1/τ}}$ ,
where τ is a temperature parameter that controls the level of exploration. The search tree is reused
at subsequent time-steps: the child node corresponding to the played action becomes the new root
node; the subtree below this child is retained along with all its statistics, while the remainder of
the tree is discarded. AlphaGo Zero resigns if its root value and best child value are lower than a
threshold value $v_{resign}$ ."

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> -    "上面说过，通过MCTS算出该下哪一步棋。然后接着再经过1600次模拟算出下一步棋，如此循环直到分出胜负，这样一整盘棋就下完了，这就是一次完整的自对弈过程，那么MCTS就相当于人在大脑中思考。我们把每步棋的局面$s_t$、算出的action概率向量$π_t$和胜率$z_t$（就是返回值value）保存下来，作为棋谱数据训练神经网络。"
oops, seems you removed Chinese text here by mistake, please restore it.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "The input of the neural network is the position s, and the output is the predicted action probability vector p and the winning rate v. The formula: $(p,v) = f_{θ_i} (s)$. The training goal is to
It's better to use "neural network action probability p" instead of "neural network walk probability p".
And for the translations of "Specifically, the parameter θ is adjusted by the loss function l of the sum of the mean square error and the cross-entropy loss through gradient descent, $l = (z-v)^2- π^T log p + c||θ||^2$, where c is the parameter that controls the L2 weight regularization level (to prevent overfitting)."

The original paper said:
"Specifically, the parameters θ are adjusted by gradient descent on a loss function l that sums over mean-squared error and cross-entropy losses respectively, $l = (z-v)^2- π^T log p + c||θ||^2$ where c is a parameter controlling the level of L2 weight regularisation (to prevent overfitting)."

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "So far, this paper basically introduces almost the same, and some details of training and optimization are not introduced here. The process is that the neural network first randomly initializes
The translations of "this paper basically introduces almost the same" for "这篇论文基本上介绍的差不多了".
What I mean is almost finished or almost completed or almost done.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Chess is different. Various characteristic planes are added to indicate different situations. The king and the rook are transposed, how many rounds have not been progressed (there is no game), a
1. please replace "characteristic" to "feature" in the whole doc.
original paper is here: https://arxiv.org/pdf/1712.01815.pdf
2. The translations of "The king and the rook are transposed" for "王车易位", should be "Castling", please refer to the wikipedia: https://zh.wikipedia.org/zh-hans/%E7%8E%8B%E8%BB%8A%E6%98%93%E4%BD%8D
3. about "there is no game" for "没有吃子", "吃子" in English is "capture piece" (please refer to http://wxf.ca/xq/computer/XIANGQI_TERMS_IN_ENGLISH.pdf), so we should use "there is no capture pieces" to instead. 
4. "等等" means etc not "wait".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "For Go, every chess piece is the same and all of the same type. There are 6 types of chess pieces: rook, horse, bishop, queen, king, and pawn. How do you express it on the characteristic plane?
1. Replace "horse" to "knight" is better I think.
2. About "and each plane is used to represent different types of chess pieces. The position on the chessboard."
How about translate to this: "and each plane is used to represent the position of different types of chess pieces on the chessboard."

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "The above is all that was introduced. For more details, such as how many optimization parameters are set, how much learning rate annealing is set, etc., please read the paper."
Let's use "such as how to set optimization parameters and learning rate annealing, etc., " instead of "such as how many optimization parameters are set, how much learning rate annealing is set, etc.,", what do you think?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "To implement the neural network first, then the input features must be designed first. In fact, similar to chess, chess pieces are divided into: rook, horse, artillery, bishop, soldier, general,
Based on the wikipedia for Chinese chess (Xiangqi) definition: https://en.wikipedia.org/wiki/Xiangqi
"炮" is "Cannon", to instead of "artillery".
"士" is "Advisor", to instead of "soldier".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "The next step is to define the input probability vector pi (π). The length of the vector needs to be determined, which means that the set length of all legal walkers needs to be determined. The
please replace "legal walkers" to "legal moves" for "合法走子"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "# Create all legal pawns UCI, size 2086\n",
please replace "legal pawns" to "legal moves" for "合法走子"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "self.momentum = 0.9\n",
Note: somehow this line is not wrap the line, Display on the same line as the next line

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "inputs_batches = tf.split(self.inputs_, self.num_gpus, axis=0)\n",
**Note**: this three lines are combined into one line to displayed, please modify it

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        with tf.device('/gpu:%d' % i):   \n",
Note: you changed the indentations, it will let script cannot work
Please modify this whole code cell

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "                    # Key points! The construction of the arithmetic graph must be written separately in the new function, so that the operation will not go wrong, otherwise TensorFlow will prom
1. Use "Computational graph" instead of "arithmetic graph" and "calculation graph"
2. And also this line merge multiple line in one line, please change it.
3. Seems the code in this line is duplicated with upper line, please take care of it

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "This is completely implemented in accordance with the neural network structure described in the paper. You can compare the structure diagram above, which is a one-to-one correspondence. The slig
How about use "if your computer is powerful" instead of "if your computer is strong"?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "    # 策略头 # Strategy header\n",
please use "policy head" here as the paper said for the whole doc

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        self.policy_head.append(policy_head)    # 保存多个gpu的策略头结果（走子概率向量）# Save the strategy header results of multiple GPUs \n",
policy head

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        if is_kill_move(last_state, self.game_borad.state) == 0:    # 刚刚下的棋是否吃子了  # Did the chess just play have a piece?\n",
"吃子" is "capture piece"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "            # 条件满足说明将/帅被吃了，游戏结束  # If the conditions are met, the general/shuai was eaten, and the game is over\n",
I am not sure capture piece also can called eaten in English, or use killed or captured?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        elif self.game_borad.restrict_round >= 60:  # 60回合没有进展（吃子），平局  # 60 rounds did not progress (take the child), draw\n",
"吃子" is "capture piece"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        # 认输的部分没有实现  # The part of confession is not implemented\n",
How about use "resignation" instead of "confession"?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        # When training, you can explore more possibilities of walking by adding noise\n",
use "move" instead of "walking"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        act = np.random.choice(actions, p=probs)     # 通过节点访问量的softmax选择最大可能性的走子  # Select the most likely mover through the softmax of node visits\n",
The translations of "most likely mover" for"最大可能性的走子". 
It is better to use "move of max possibility" instead.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        action_probs, value = self.forward(positions)    # 通过神经网络预测走子概率  # Predict the probability of walking through a neural network\n",
use "move" instead of "walking"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        if self.is_black_turn(current_player):    # 判断走子概率是否需要根据先手/后手进行转换  # Determine whether the probability of a move needs to be converted according to the first hand/back hand\n",
about "first hand/back hand":
"先手" is "initiative"
"后手" is "passive"
please refer to http://wxf.ca/xq/computer/XIANGQI_TERMS_IN_ENGLISH.pdf

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        node.expand(moves, action_probs)    # 扩展节点  # Expansion node\n",
Expand node

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> -    "    with await self.sem:    # 异步执行树搜索，共16个线程\n",
You removed "共16个线程" by mistake, please restore it.

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "    with await self.sem:    # 异步执行树搜索， # Asynchronous execution tree search, a total of 16 threads\n",
How about use "Asynchronously execute tree search"?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        # All this is asynchronous\n",
"All" or "All of "?

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "        elif restrict_round >= 60:    # 60回合无进展（吃子），平局 # 60 rounds no progress (take a child), draw\n",
"吃子" is "capture piece" instead of "take a child".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "# The parameter is all legal moves, and the probability vector predicted by the neural network action_probs\n",
"and the probability vector predicted by the neural network action_probs" should be "and the probability vector action_probs predicted by the neural network"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "    self.Q = self.W / self.N  # 更新平均行动价值  # Update average action value\n",
"平均行动价值" is "mean action-value" instead of "average action value".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Let’s talk about a~c, MCTS essentially means that we maintain a tree. Each node of this tree saves information on how to move each situation. The information is that N(s, a) is the number of vis
"平均行动价值" is "mean action-value" instead of "average action value".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "That is to say, after selecting a node through Select, the number of visits of this node N is artificially increased, and the total action value W of the node is reduced, because the average act
"平均行动价值" is "mean action-value" instead of "average action value".

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Let me talk about the training situation, because I started training with the whiteboard. At the beginning, it was chaotic. Learning to play chess from chaotic experience requires a lot of games
"象" is "bishop" instead of "elephants"
"士" is "Advisor" instead of "warriors"
use "It still play chess badly" instead of "I still play chess badly"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Reference material¶"
please remove "¶"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "Today’s sharing is here, please advise~"
How about use "That’s all for today’s sharing, please advise~"

2021-11-23 01:46 UTC, chengstone commented on cchess-zero.ipynb
> +    "                    # 划重点！运算图的构建一定要单独写在新的函数中，这样运行才不会出错，否则TensorFlow会提示不能重复使用变量。**\n",
"**" in the begging is missing

2021-11-23 01:46 UTC, chengstone commented on ChessBoard.py
> +        # 吃子 # Take Piece
"吃子" is "capture piece"

2021-11-23 01:46 UTC, chengstone commented on README.en.md
> +Because my model is not fully trained, I only trained it less than 4K times. The model has just learned to use elephants and soldiers to defend. In short, I still play chess badly.
"象" is "bishop" instead of "elephants"
"士" is "Advisor" instead of "soldiers"
use "It still play chess badly" instead of "I still play chess badly"

2021-11-23 01:46 UTC, chengstone commented on README.en.md
> + - --human_color specifies the color of the human chess player, w is the first move, b is the second move
"先手" is "initiative" instead of "first move"
"后手" is "passive" instead of "second move"
please refer to http://wxf.ca/xq/computer/XIANGQI_TERMS_IN_ENGLISH.pdf

2021-11-23 01:46 UTC, chengstone commented on README.en.md
> +# Permission
Here should use "License" instead of "Permission"

2021-11-23 01:46 UTC, chengstone commented on Mastering_Chess_and_Shogi_by_Self-Play_with_a_General_Reinforcement_Learning_Algorithm.ipynb
> -    "# 用通用强化学习算法自我对弈，掌握国际象棋和将棋"
You don't need to translate this page, because the original paper is here:
https://arxiv.org/pdf/1712.01815.pdf

2021-12-06 19:29 UTC, ycechungAI commented
sorry for delay, made the changes.

2022-03-26 15:50 UTC, closed without merging